### ISSUE TITLE
Doesnt automatically go into tharete mode plus scrollbar viisble.

### ISSUE THREAD

**Issue by somokol** [rotemdan/MaximizerForYouTube#1]
I'm using the latest  MaximizerForYouTube userscript on Firefox 56.0.2 with Greasemonkey and YouTubes new material design and dark skin activated.

Two problems, which I'm unsure if it's a bug or normal operation.

1. When I open a YouTube video it doesn't automatically go into Theater mode. I have to click the theater mode button, then it appears to work fine.

2. When I'm in Theater mode, I can see the YouTube scrollbar on the right side. Is this normal? If so, can it be made to remove the scrollbar when in theater mode?

Thanks for this script, it freaking awesome!

**Comment by rotemdan** [comment]
Hi, sorry for the very late reply. I've been away from GitHub for several months now.

1. This is the intended behavior, so that the normal mode can be used as well (for example, in live videos - to see the chat while watching the videos). In the previous version of the script it did change to theater mode automatically and I considered that a limitation.

2. The scrollbar is normal (it is just a normal player page with the video resized to fill the viewport), but in the future I will consider hiding it (as an option possibly), or replace it with a less intrusive one - though as far as I'm aware custom scrollbars (through CSS I believe) are only available in Chrome at the moment.

**Comment by rotemdan** [comment]
On WebKit browsers (Chrome, Chromium, Safari) the scrollbar is now styled to be significantly thinner and darker. This is only supported on WebKit because it uses WebKit specific CSS attributes (there are no equivalent ones for Firefox, as far as I know):

This is the current style that is applied to achieve this effect (improvement suggestions welcome):
```css
::-webkit-scrollbar {
	width: 10px;
	background-color: #000000;
}
												
::-webkit-scrollbar-track {
	border-radius: 10px;
	background: rgba(0,0,0,0.1);
	border: 1px solid #383838;
}
						  
::-webkit-scrollbar-thumb {
	border-radius: 10px;
	background: linear-gradient(left, #fff, #e4e4e4);
	border: 1px solid #5b5b5b;
}
						  
::-webkit-scrollbar-thumb:hover {
	background: #fff;
}
						  
::-webkit-scrollbar-thumb:active {
	background: linear-gradient(left, #22ADD4, #1E98BA);
}
```

To support Firefox as well, it would require using a separate, JavaScript based solution. Having searched for a while I haven't found one that is reliable enough and can be applied to the whole page (rather than only within a specific element). Being primarily a Firefox user myself, I would certainly appreciate having this feature in the future though.
